### ISSUE TITLE
Get more than 25 URLs

### ISSUE THREAD

**Issue by MrUltimate** [pdehaan/fetch-subreddit#11]
Hi,

I know this is an old package and might not be maintained anymore, but I was wondering if there's a way to get more than 25 URLs from a subreddit?

**Comment by pdehaan** [comment]
@MrUltimate probably not with this package, but I think you can pass a `?limit=` to the Reddit JSON feed URL and get 100 results maximum; for example https://www.reddit.com/r/funny/.json?limit=100

**Comment by MrUltimate** [comment]
That's it! Thanks!
